version: "3.9"
services:
  postgres:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=zentest
      - POSTGRES_PASSWORD=zentest
    ports:
      - "5436:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  minio:
    image: "minio/minio:RELEASE.2022-11-26T22-43-32Z"
    environment:
      - MINIO_ROOT_USER=zentest
      - MINIO_ROOT_PASSWORD=zentest1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    command: server --console-address ":9001" /data
